### ISSUE TITLE
MTConnect Nodeset can't be Imported

### ISSUE THREAD

**Issue by jwise-cesmii** [cesmii/ProfileDesigner#3]
**Repro Steps**

- Log-in to Profile Designer
- Choose "Import Profile" from the Welcome Wizard
- Provide the official MTConnect Nodeset as downloaded (raw) from here: https://github.com/OPCFoundation/UA-Nodeset/blob/v1.04/MTConnect/Opc.Ua.MTConnect.NodeSet2.xml
- Observe error in screenshot:
![MTConnect](https://user-images.githubusercontent.com/57234292/154139398-defb73f3-00b0-4ee2-a4c8-00ec918e8359.png)
t

**Comment by MarkusHorstmann** [comment]
Investigating.
